apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: core
  source:
    repoURL: <GIT_REPOSITORY_GIT_URL>
    targetRevision: HEAD
    path: clusters/<PRIMARY_CLUSTER_NAME>/core-services/components/kube-system/aws-load-balancer-controller
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

