apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: sonarqube
  namespace: argocd
spec:
  destination:
    namespace: sonarqube
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: sonarqube
    repoURL: https://SonarSource.github.io/helm-chart-sonarqube
    targetRevision: 10.2.0
    helm:
      releaseName: sonarqube
      values: |
        image:
          pullSecrets:
            - name: docker-config
        postgresql:
          image:
            repository: bitnamilegacy/postgresql
            tag: "11.14.0"
          persistence:
            enabled: true
            accessMode: ReadWriteOnce
            size: 20Gi
            storageClass: gp3
        persistence:
          enabled: false
        plugins:
          install:
            # https://docs.sonarsource.com/sonarqube/latest/instance-administration/plugin-version-matrix/
            # pottentially interesting plugin not compatible with v10.* yet
            # https://github.com/mc1arke/sonarqube-community-branch-plugin
            - "https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/4.0.0/sonar-dependency-check-plugin-4.0.0.jar"
            # core dump with yaml plugin, debug later
            # - "https://github.com/sbaudoin/sonar-yaml/releases/download/v1.8.0/sonar-yaml-plugin-1.8.0.jar"
            - "https://github.com/vaulttec/sonar-auth-oidc/releases/download/v2.1.1/sonar-auth-oidc-plugin-2.1.1.jar"
            - "https://github.com/checkstyle/sonar-checkstyle/releases/download/10.12.3/checkstyle-sonar-plugin-10.12.3.jar"
        ingress:
          enabled: false
        account:
          adminPasswordSecretName: "sonarqube-admin"
        labels:
          <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
          <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          <PLATFORM_NAME_KEBAB>.metadata.service: code-quality.sonarqube
          <PLATFORM_NAME_KEBAB>.metadata.chart-version: 10.2.0
          <PLATFORM_NAME_KEBAB>.metadata.version: 10.2.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
