apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: v1.16.3
    helm:
      releaseName: harbor
      values: |
        externalURL: https://<REGISTRY_INGRESS_URL>
        imagePullSecrets:
          - name: docker-config
        expose:
          type: ingress
          tls:
            enabled: true
            certSource: secret
            secret:
              secretName: "harbor-tls"
          ingress:
            hosts:
              core: <REGISTRY_INGRESS_URL>
            className: alb
            annotations:
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/certificate-arn: <ACM_CERTIFICATE_ARN>
              alb.ingress.kubernetes.io/group.name: <ALB_INGRESS_GROUP_NAME>
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
              alb.ingress.kubernetes.io/security-groups: <ALB_SECURITY_GROUPS>
              alb.ingress.kubernetes.io/subnets: <ALB_PUBLIC_SUBNETS>
              alb.ingress.kubernetes.io/tags: environment=<PRIMARY_CLUSTER_NAME>,provisioned-by=<PLATFORM_NAME_KEBAB>
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
              kubernetes.io/ingress.class: alb
            labels:
              <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
              <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
              <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
              <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
              <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        database:
          type: internal
          internal:
            resources:
              requests:
                cpu: 300m
                memory: 512Mi
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        registry:
          # set the service account to be used, default if left empty
          serviceAccountName: ""
          automountServiceAccountToken: false
          registry:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
          controller:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        portal:
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        persistence:
          enabled: true
          imageChartStorage:
            type: filesystem
            filesystem:
              rootdirectory: /storage
          persistentVolumeClaim:
            registry:
              size: 250Gi
        core:
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        jobservice:
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        redis:
          type: internal
          internal:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        notary:
          enabled: false
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        trivy:
          # enabled the flag to enable Trivy scanner
          enabled: true
          podLabels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: oci-registry.harbor
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 1.16.3
            <PLATFORM_NAME_KEBAB>.metadata.version: 2.12.3
        updateStrategy:
          type: Recreate
        existingSecretAdminPassword: harbor-admin
        existingSecretAdminPasswordKey: HARBOR_ADMIN_PASSWORD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
