---
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: kubevirt-common-labels
labels:
  <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: "platform"
  <PLATFORM_NAME_KEBAB>.metadata.owner: "<GITOPS_REPOSITORY_NAME>-admin"
  <PLATFORM_NAME_KEBAB>.metadata.service: "virtualization.kubevirt"
  <PLATFORM_NAME_KEBAB>.metadata.version: "1.2.2"
fieldSpecs:
- path: metadata/labels
  create: true
- path: spec/template/metadata/labels
  create: true
  kind: Deployment
