apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: tracee
  namespace: argocd
spec:
  destination:
    namespace: tracee
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: tracee
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.23.1
    helm:
      releaseName: tracee
      values: |
        config:
          metrics: true
        labels:
          <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
          <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          <PLATFORM_NAME_KEBAB>.metadata.service: runtime-security.tracee
          <PLATFORM_NAME_KEBAB>.metadata.chart-version: 0.23.1
          <PLATFORM_NAME_KEBAB>.metadata.version: 0.23.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
