apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '10'
  name: trivy
  namespace: argocd
spec:
  destination:
    namespace: trivy
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: trivy-operator
    repoURL: https://aquasecurity.github.io/helm-charts/
    targetRevision: 0.28.1
    helm:
      releaseName: trivy-operator
      values: |
        image:
          pullSecrets:
            - name: docker-config
        trivy:
          ignoreUnfixed: false
          labels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: runtime-vulnerability-analysis
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 0.28.1
            <PLATFORM_NAME_KEBAB>.metadata.version: 0.28.1
        serviceMonitor:
          # enabled determines whether a serviceMonitor should be deployed
          enabled: true
          labels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: runtime-vulnerability-analysis
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 0.28.1
            <PLATFORM_NAME_KEBAB>.metadata.version: 0.28.1
        operator:
          metricsVulnIdEnabled: true
          labels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: runtime-vulnerability-analysis
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 0.28.1
            <PLATFORM_NAME_KEBAB>.metadata.version: 0.28.1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
