apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: v3.4.1
    helm:
      releaseName: kyverno
      values: |
        commonLabels:
          <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
          <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
          <PLATFORM_NAME_KEBAB>.metadata.service: policy-engine.kyverno
          <PLATFORM_NAME_KEBAB>.metadata.chart-version: 3.4.1
          <PLATFORM_NAME_KEBAB>.metadata.version: 1.14.1
        global:
          imagePullSecrets:
           - name: docker-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
