apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policy-reporter
  namespace: argocd
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: core
  source:
    chart: policy-reporter
    repoURL: https://kyverno.github.io/policy-reporter
    targetRevision: v3.1.4
    helm:
      releaseName: policy-reporter
      values: |
        global:
          labels:
            <PLATFORM_NAME_KEBAB>.cost-allocation.cost-center: platform
            <PLATFORM_NAME_KEBAB>.metadata.owner: <GITOPS_REPOSITORY_NAME>-admin
            <PLATFORM_NAME_KEBAB>.metadata.service: policy-engine.kyverno-policy-reporter
            <PLATFORM_NAME_KEBAB>.metadata.chart-version: 3.1.4
            <PLATFORM_NAME_KEBAB>.metadata.version: 3.1.1          
        ui:
          enabled: true
        kyvernoPlugin:
          enabled: true
        metrics:
          enabled: true
        global:
          # available plugins
          plugins:
            # enable kyverno for Policy Reporter UI and monitoring
            kyverno: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true